### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#1]
- [x] Nama sekolah belum tampil
- [ ] Search by kategori dan tipe dokumen belum bisa
- [x] Aksi (Detail, Edit, Verifikasi, Perpanjangan)

**Comment by anggarasaja** [comment]
ini jd di assigned apa enggak ? wkwk

**Comment by kartikads** [comment]
Jadi, tapi gue bingung assign ke siapa kmrn. Krn kmrn cuma bisa pilih satu orang hahaha. Yg penting selesailah. Siapapun yg ngerjain xp

**Comment by anggarasaja** [comment]
oia cuma bisa satu ya

**Comment by anggarasaja** [comment]
https://github.com/kartikads/ch/commit/8d560f491a82ff5cf1ca0707d427a2934126127d

**Comment by pertiwi** [comment]
Yg gw kerjain blm di pull ka nanti ya

**Comment by pertiwi** [comment]
Yg gw kerjain blm gw pul ka nanti ya
