### ISSUE TITLE
Revisi 06 February 2015

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#11]
- [x] Filter Pencarian
- [x] Izin Baru Siswa & Izin Pekerja -> uncheck field
- [x] Izin Pekerja -> Informasi Ijasah "required"
- [x] Izin Pekerja -> placeholder "Mulai Belajar"
- [x] Izin Pekerja -> Label "Tanggal Pengajuan & Tanggal Berakhir"
- [x] Surat Unit Utama -> Pindahin panel "Tambah Siswa"
- [x] Surat Unit Utama "Pekerja"
- [x] Grafik -> Ganti JS
- [x] Account Information -> di hide
- [x] Grafik -> Negara, Kategori, Jenis
- [x] Laporan -> kalau lebih dari 1 orang bentuk lampiran tabel

**Comment by kartikads** [comment]
@anggarasaja

**Comment by kartikads** [comment]
@anggarasaja @pertiwi  
- filter search yang kategori error ni, errornya "Column 'kategori' in where clause is ambiguous"
- untuk laporan lebih dari 1 orang kondisinya gimana aja ya?

**Comment by anggarasaja** [comment]
laporan lebih dari 1 orang, kalo pilih si A ternyata ada orang lain dengan nomor surat unit utama yang sama dgn si A maka akan tercetak dalam bentuk tabel (lampiran)
