### ISSUE TITLE
Buat Izin Belajar

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#2]
- [ ] Tab Step di disable
- [x] step ke 4 (verifikasi di hide/hapus) dan tombol save and finish di step 4, dipindah ke step 3
- [x] finish, redirect ke home

**Comment by anggarasaja** [comment]
https://github.com/kartikads/ch/commit/5f3af49c14c92740b68d9a12942368c6693e2d0d

poin 2 dan 3.

mohon ditest lagi.

**Comment by kartikads** [comment]
sudah dicoba (ok)

**Comment by kartikads** [comment]
tabs disable abaikan dulu ya @anggarasaja @pertiwi kerjain yang lain dulu.
