### ISSUE TITLE
Surat Rekomendasi

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#3]
- [x] Search by nama sekolah & institusi
- [x] Bahasa Inggris diubah ke bahasa indonesia
- [x] Saat menambah student -> Kode + Nama

**Comment by anggarasaja** [comment]
poin ke 1 udah kan ya

**Comment by anggarasaja** [comment]
https://github.com/kartikads/ch/commit/52cb7a052880f049fcddf2318f8576d80d6f8598

untuk poin ke 3
