### ISSUE TITLE
View Izin Belajar

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#4]
- [x] Rapikan style
- [x] B.Inggris ke b.indonesia
- [x] Error tab karena tab studi info
- [x] Hilangkan button save

**Comment by kartikads** [comment]
untuk point ke-3 @anggarasaja  yaa.

**Comment by anggarasaja** [comment]
https://github.com/kartikads/ch/commit/822ed900cca08652e47a5f4b0bcd0e00b090a9a1

untuk poin ke-3
