### ISSUE TITLE
Buat Izin Bekerja

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#5]
- [x] konten ubah ke bahasa indonesia
- [x] tambah 1 panel (informasi ijasah) di step 'data diri' isinya:
  - input text (institusi, jurusan)
  - input select (strata -> D3, S1, S2, S3)
  - input number (tahun ijasah)
- [x] di step 'informasi bekerja' tambah inputan:
  - input select (jenis tempat kerja -> SPK, Negeri, Swasta)
  - input no. izin operasional
  - upload izin operasional
  - input no.RPTKA
  - upload RPTKA
- [x] hide step 4, dan pindahkan tombol finish di step 3 (sama seperti izin belajar)

**Comment by kartikads** [comment]
@pertiwi point 1 tiwi ya

**Comment by pertiwi** [comment]
Okay siap
