### ISSUE TITLE
Perpanjangan Izin Belajar

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#6]
- [x] konten ubah ke bahasa indonesia
- [x] step informasi studi error
- [ ] dibuat 3 step -> seperti izin belajar

**Comment by kartikads** [comment]
@anggarasaja tolong dibantu juga

**Comment by anggarasaja** [comment]
https://github.com/kartikads/ch/commit/9bae8986fc1101a509dd6ad708b6505389aa7b10

perpanjangan izin jadi 3 tab.

NOTE : sejak commit diatas, untuk format username mahasiswa berubah jadi "tanggal-nama_sekolah-id" (sebelumnya "tanggal--id"). jadi kalo mau perpanjangan tp gak bisa, coba diliat username yang ada di tab ke 3 dengan username yang ada di database apakah sama ? kalo beda, bisa disamakan dulu atau bikin data dummy baru
