### ISSUE TITLE
Perpanjangan Izin Bekerja

### ISSUE THREAD

**Issue by kartikads** [kartikads/ch#7]
- [x] tambahkan upload file laporan di 'dokumen pendukung' 
- [x] tambahkan panel 'KITAS' di 'dokumen pendukung' isinya:
  - upload file kitas
  - input no kitas
  - masa berlaku kitas (dari - sampai)
- [x] tambahkan panel 'IMTA' di 'dokumen pendukung' isinya:
  - input no imta
  - upload file imta
- [x] tambahkan panel 'Surat Tanda Melapor Diri' di 'dokumen pendukung' isinya:
  - input no surat tanda melapor diri
  - upload file surat tanda melapor diri

**Comment by kartikads** [comment]
@pertiwi tolong dibantu juga

**Comment by anggarasaja** [comment]
![kitas](https://cloud.githubusercontent.com/assets/5020213/12475592/87dfdc2c-c056-11e5-8c96-509f31a6a600.png)
yang poin 2 kan udah ada tuh kak, bedanya apa kak ?

**Comment by kartikads** [comment]
Ini kyknya gue tulis sebelum ada deh apa emang udh ada? Hehe brarti sama. 
Oia merujuk dengan revisi terbaru, untuk upload2 itu diganti sama checklist ya. Kecuali surat unit utama, passport, sama kitas klo di perpanjangan.

**Comment by anggarasaja** [comment]
Surat Tanda Melapor Diri dan SKLD/SKJ/STM itu kayanya sama ya ? 
![screenshot-localhost 2016-02-03 14-22-00](https://cloud.githubusercontent.com/assets/5020213/12775543/9c232448-ca81-11e5-9298-756b9e88bfcf.png)
